# This file controls the AWS CodeBuild

version: 0.2
phases:
  pre_build:
    commands:
    - echo "Entered the pre-build phase"
  build:
    commands:
    - echo "Entered build phase"
    - mvn clean install
  post_build:
    commands:
    - echo "Entered the post-build phase"
artifacts:
  files:
    - target/03-spring-boot-web-application-h2-0.0.1-SNAPSHOT.war
